language: rust

language: rust

rust:
    - stable
    - nightly
    - beta

os:
    - linux

script:
    - env
    - cargo test && rustup target add wasm32-unknown-unknown && cargo build --target=wasm32-unknown-unknown
