[package]
name = "plotters"
version = "0.1.0"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"
license = "MIT"
descrption = "The Plotting Library in Rust"

[dependencies]
svg = "0.5.12"
image = "0.21.1"
rusttype = "0.7.6"
font-loader = "0.8.0"
lazy_static = "*"
