[package]
name = "plotters"
version = "0.1.2"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Anoter Plotting Library in Rust"
repository = "https://github.com/38/plotters"

[dependencies]
svg = "0.5.12"
image = "0.21.1"
rusttype = "0.7.6"
font-loader = "0.8.0"
lazy_static = "^1.2"
chrono = "0.4.6"
