[package]
name = "plotters"
version = "0.2.7"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Plot Drawing Library in Pure Rust for both native and WASM applications"
repository = "https://github.com/38/plotters"
keywords = ["WebAssembly", "Visualization", "Plotting", "Drawing"]
categories = ["visualization", "wasm"]
readme = "README.md"
exclude = ["doc-template/*"]

[dependencies]
chrono = { version = "0.4.9", optional = true }
svg = { version = "0.6.0", optional = true }
num-traits = { version = "^0.2", optional = true }
palette = { version = "^0.4", default-features = false, optional = true }
gif = { version = "^0.10.3", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rusttype = "0.7.6"
font-loader = "0.8.0"
lazy_static = "^1.2"
piston_window = {version = "0.96.0", optional = true}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.image]
version = "0.22.3"
optional = true
default_features = false
features = ["jpeg", "png_codec", "bmp"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.4", features = ['Document', 'Element', 'HtmlElement', 'Node', 'Window', 'HtmlCanvasElement', 'CanvasRenderingContext2d'] }
js-sys= "0.3.4"
wasm-bindgen = "0.2.43"

[features]
default = ["bitmap", "svg", "chrono", "palette_ext", "make_partial_axis", "gif_backend"]
palette_ext = ["palette", "num-traits"]
bitmap = ["image"]
gif_backend = ["bitmap", "gif"]
datetime = ["chrono"]
evcxr = ["svg"]
piston = ["piston_window"]
make_partial_axis = ["num-traits"]


[dev-dependencies]
rand = "^0.7.2"
itertools = "^0.8.0"
rand_distr = "0.2.2"
