name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check WASM Target Compiles
      run: rustup target add wasm32-unknown-unknown && cargo build --verbose --target=wasm32-unknown-unknown
    
      
